# Generated by Django 6.0 on 2025-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_patient_name_testimonial_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='bio',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='highest_degree',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
