# Generated by Django 6.0 on 2026-01-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contactmessage_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='HomePageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(upload_to='home/banner/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the item in carousel')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Home Page Carousel Item',
                'verbose_name_plural': 'Home Page Carousel Items',
                'ordering': ['order'],
            },
        ),
    ]
