# Generated by Django 6.0 on 2026-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_homepage_banner_image_alter_homepage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel_items',
            field=models.JSONField(blank=True, default=list, help_text='Add multiple carousel items as a JSON array. Each item should have title, subtitle, banner_image_url, and order.'),
        ),
        migrations.DeleteModel(
            name='HomePageItem',
        ),
    ]
