# Generated by Django 6.0 on 2026-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homepage_carousel_items_delete_homepageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel_items',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(default='home/default_banner.jpg', upload_to='home/banner/'),
        ),
    ]
