# Generated by Django 6.0 on 2026-01-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_servicesmenus_parent_service_delete_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
