# Generated by Django 5.0.3 on 2026-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(blank=True, default='home/default_banner.jpg', null=True, upload_to='home/banner/'),
        ),
    ]
