# Generated by Django 5.0.3 on 2026-04-01 15:47

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_doctor_image_alter_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_us_image')),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
