# Generated by Django 5.1.4 on 2026-04-14 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutus_doctor_nmc_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page Slide', 'verbose_name_plural': 'Home Page Slides'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
