# Generated by Django 5.1.4 on 2026-05-01 02:03

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_homepage_options_alter_doctor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='journey_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='journey_subtitle',
            field=models.CharField(blank=True, default='From humble beginnings to a leading healthcare institution', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='journey_title',
            field=models.CharField(blank=True, default='Our Journey', max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_leadership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='leadership_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g., Heart, Target)', max_length=50)),
                ('description', models.TextField()),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='core.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='facility_image')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('event', models.TextField()),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.aboutus')),
            ],
        ),
    ]
