# Generated by Django 5.0.3 on 2026-05-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aboutus_journey_description_aboutus_journey_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='leadership_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
