# Generated by Django 5.0.3 on 2026-05-01 02:24

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_doctor_leadership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='vision',
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='leader_image')),
                ('nmc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.aboutus')),
            ],
        ),
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
