# Generated by Django 5.0.3 on 2026-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_name_contactmessage_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['order'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
